image: jakzal/phpqa:php7.4

before_script:
  - composer install

cache:
  paths:
    - vendor/

stages:
  - PHPUnit_Tests

phpunit:
  stage: PHPUnit_Tests
  script:
    - php ./vendor/bin/simple-phpunit --coverage-text --colors=never
  allows_failure: false
