image: jakzal/phpqa:php7.4

before_script:
  - apt update -y
  - apt-get install libjpeg-dev libjpeg62-turbo-dev libfreetype6-dev -y
  - docker-php-ext-configure gd --with-jpeg --with-freetype
  - docker-php-ext-install -j$(nproc) gd 
  - composer install

cache:
  paths:
    - vendor/

stages:
  - PHPUnit_Tests

phpunit:
  stage: PHPUnit_Tests
  script:
    - php ./vendor/bin/simple-phpunit --coverage-text --colors=never
  allow_failure: false
