image: jakzal/phpqa:php7.4

before_script:
  - composer install

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install libjpeg-dev libpng-dev -yqq
  - docker-php-ext-install gd

stages:
  - PHPUnit_Tests

phpunit:
  stage: PHPUnit_Tests
  script:
    - php ./vendor/bin/simple-phpunit --coverage-text --colors=never
  allow_failure: false
