image: php:8.1-cli

before_script: 
  - apt update -y
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - apt-get install libjpeg-dev libjpeg62-turbo-dev libfreetype6-dev libzip-dev zip -y
  - docker-php-ext-configure gd --with-jpeg --with-freetype
  - docker-php-ext-install -j$(nproc) gd zip
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer update
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  - apt-get install nodejs -y
  - apt-get install npm -y
  - npm install --global yarn -y
  - yarn add --dev @symfony/webpack-encore
  - yarn encore production --progress

cache:
  paths:
    - vendor/

stages:
  - PHPUnit_Tests

phpunit:
  stage: PHPUnit_Tests
  script:
    - php bin/console cache:clear --env=test
    - php -d xdebug.mode=coverage ./vendor/bin/simple-phpunit --coverage-text --colors=never
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  allow_failure: false
