name: php-cs-fixer

on: [push]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga:2.17.5 # php version 7.4.14
      with:
        args: --config=.php-cs-fixer.dist.php --diff --dry-run
