name: phpstan

on: [push]

jobs:
  Phpstan_src:
    name: Phpstan_src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project v2
        uses: actions/checkout@v2
            
      # composer-installer-action
      - uses: actions/checkout@master
      - uses: nanasess/composer-installer-action@master
      - run: composer install
      - run: php -d memory_limit=-1

      - name: PHPStan (php-action)
        uses: php-actions/phpstan@v3
        with:
          path: src/
          php_version: 7.4.5
          configuration: phpstan-ci.neon
          version: 9.5.20
