name: phpstan-tests

on: [push]

jobs:
  Phpstan_tests:
    name: Phpstan_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project v2
        uses: actions/checkout@v2
            
      # composer-installer-action
      - uses: actions/checkout@master
      - uses: nanasess/composer-installer-action@master
      - run: composer install
      - run: composer require phpunit/phpunit --dev ^9
      - run: php -d memory_limit=-1

      - name: OSKAR PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
        with:
          args: analyze tests/ -c phpstan-ci.neon
