name: phpstan

on: [push]

jobs:
  Phpstan_src:
    name: Phpstan_src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project v2
        uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      # phpstan action
      - name: PHPStan (php-action)
        uses: php-actions/phpstan@v3
        with:
          version: 1.5.7
          php_version: 7.4.5
          path: src/
          configuration: phpstan-ci.neon
